 Hi, I’m @Cohcohnuhtava
 I’m interested in helping you on server things for discord.
 I’m currently learning on how to make your own bot. 
 I’m looking to collaborate on discord
 How to reach me Yelena Snk#1842 dm me on discord.

<!---
Cohcohnuhtava/Cohcohnuhtava is a ✨ special ✨ repository because its `README.md` (this file) appears on your GitHub profile.
You can click the Preview link to take a look at your changes.
--->
